vtk_module(vtkRobartsVisualization
  GROUPS
    Visualization
  DEPENDS
    vtkRobartsCommon
    vtkInteractionStyle
    vtkRenderingFreeType
    vtkRendering${VTK_RENDERING_BACKEND}
    vtkRenderingGL2PS${VTK_RENDERING_BACKEND}
    ${VTK_EXTRA_MODULES}
  )