vtk_module(TFUIKohonen
  GROUPS
    Examples
  DEPENDS
    TFUICommon 
    vtkCudaVisualization 
    vtkCudaImageAnalytics 
    vtkCudaCommon 
    vtkRenderingVolume${VTK_RENDERING_BACKEND} 
    vtkRenderingCore 
    vtkFiltersCore 
    vtkImagingCore 
    vtkIOImage 
    vtkCommonCore 
    vtkGUISupportQt
    ${VTK_EXTRA_MODULES}
  EXCLUDE_FROM_WRAPPING
  )