vtk_module(TFUIGradient
  GROUPS
    Examples
  DEPENDS
    TFUICommon 
    vtkCudaVisualization 
    vtkCudaImageAnalytics 
    vtkCudaCommon 
    vtkRenderingVolume 
    vtkRenderingCore 
    vtkFiltersCore 
    vtkImagingCore 
    vtkIOImage 
    vtkCommonCore 
    vtkGUISupportQt
    vtkRenderingGL2PS${VTK_RENDERING_BACKEND}
    ${VTK_EXTRA_MODULES}
  EXCLUDE_FROM_WRAPPING
  )