vtk_module(TFUIGradient
  GROUPS
    Examples
  DEPENDS
    TFUICommon 
    vtkCudaVisualization 
    vtkCudaImageAnalytics 
    vtkCudaCommon 
    vtkRenderingVolume 
    vtkRenderingCore 
    vtkFiltersCore 
    vtkImagingCore 
    vtkIOImage 
    vtkCommonCore 
    vtkGUISupportQt
  EXCLUDE_FROM_WRAPPING
  )