vtk_module(MaxFlow
  GROUPS
    Utilities
  DEPENDS
    vtkFiltersCore 
    vtkImagingCore 
    vtkIOCore 
    vtkIOImage 
    vtkCommonCore 
    vtkCudaCommon 
    vtkCudaImageAnalytics 
    vtkRobartsCommon
  KIT
    vtkRobartsUtilities
  )