vtk_module(vtkCudaVisualization
  GROUPS
    Visualization
    Cuda
  DEPENDS
    vtkCudaCommon
    vtkCudaCommonStatic
    vtkRenderingVolume
    vtkRenderingVolumeOpenGL
  KIT
    vtkRobartsCuda
  EXCLUDE_FROM_WRAP_HIERARCHY
  )