vtk_module(vtkCudaVisualization
  GROUPS
    Visualization
    Cuda
  DEPENDS
    vtkCudaCommon
    vtkCudaCommonStatic
    vtkRenderingVolume
    vtkRenderingVolume${VTK_RENDERING_BACKEND}
  EXCLUDE_FROM_WRAP_HIERARCHY
  )