vtk_module(TFUIDual
  GROUPS
    Examples
  DEPENDS
    TFUICommon 
    vtkCudaVisualization 
    vtkCudaImageAnalytics 
    vtkCudaCommon 
    vtkRenderingVolume 
    vtkRenderingCore 
    vtkFiltersCore 
    vtkImagingCore 
    vtkIOImage 
    vtkCommonCore 
    vtkRenderingGL2PS${VTK_RENDERING_BACKEND}
    vtkGUISupportQt
    vtksys
    ${VTK_EXTRA_MODULES}
  EXCLUDE_FROM_WRAPPING
  )