vtk_module(FluoroPredViz
  GROUPS
    Examples
  DEPENDS
    vtkCudaCommon 
    vtkCudaVisualization 
    vtkCudaImageAnalytics 
    vtkRobartsCommon 
    vtkRenderingVolume${VTK_RENDERING_BACKEND} 
    vtkRenderingCore 
    vtkFiltersCore 
    vtkImagingCore 
    vtkInteractionWidgets 
    vtkGUISupportQt 
    vtkIOCore 
    vtkCommonCore 
    vtkIOMINC 
    ${VTK_EXTRA_MODULES}
  EXCLUDE_FROM_WRAPPING
  )