vtk_module(TFUICommon 
  GROUPS
    Examples
  DEPENDS
    vtkCudaCommon 
    vtkCudaVisualization  
    vtkRenderingVolumeOpenGL  
    vtkInteractionWidgets 
    vtksys 
    vtkIOLegacy 
    vtkIOMINC 
    vtkImagingMath 
  EXCLUDE_FROM_WRAPPING
  )